<?php

/*
* student_last_moodle_login.php
*
* Author:			Matt Rice
* Date:				2013-05-02
*
* Description:
*
* This script displays a MySQL view, rice_last_login, that shows the last login date
* of dual-enrolled students from a list generated by the dual enrollment coordinator
* (formerly Julie Fortino Shurtliff, more recently Lindsay Golden)
*
* Generated in response to Help Desk ticket #10420.
*
*
*/

require_once('constants.php');

//Define the DB object here as a constant (for ease of future changes)
define("STUDENTVIEW", "rice_last_login");

// Connect to Moodle database
$conn = mysql_connect(DB_SERVER, DB_USERNAME, DB_PASSWORD) or die("Database connection failed");
$db = mysql_select_db(DB_NAME) or die("Database selection failed");

echo "<html>\n<body>\n";
//remove charset warning
echo "<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>\n\n";

//Stylesheet - because I'm vain and want my output to look nice
$css = <<<CSS
<style type='text/css'>
	table {
	  border-collapse: collapse;
	}

	table td,th {
	  border: 1px solid #aaa;
	  padding: 0.2em;
	}

	.ralign {
	  text-align: right;
	}

</style>\n
CSS;

echo $css;

$students = get_number_of_students();

echo "<p>" . $students . " student(s) in report.</p>\n";
if (0 < $students) {
	generate_student_table();
}

echo "</body>\n</html>";

//Get the number of students in the query
function get_number_of_students()
{
	$students = 0;

	$sql = "SELECT count(*) FROM " . STUDENTVIEW;
	$rs = mysql_query($sql) or die("Query failed: $sql");

	if ($row = mysql_fetch_array($rs, MYSQL_NUM)) {
		$students = $row[0];
	}

	return $students;
}

function generate_student_table ()
{
	//Get data from DB view
	$sql = "SELECT `rep`, `lastname`, `firstname`, `student_id`, `lastlogin` FROM " . STUDENTVIEW;
	$rs = mysql_query($sql) or die("Query failed: $sql");

	//Create the HTML output
	echo "<table>\n";
	echo "<tr>\n\t<th>Rep</th>\n\t<th>Last Name</th>\n\t<th>First Name</th>\n\t<th>Last Moodle Login</th>\n</tr>\n";

	//Actual data the user cares about
	while ($row = mysql_fetch_array($rs, MYSQL_NUM)) {
		echo format_output($row);
	}

	echo "<tr>\n\t<th>Rep</th>\n\t<th>Last Name</th>\n\t<th>First Name</th>\n\t<th>Last Moodle Login</th>\n</tr>\n";
	echo "</table>\n";
}


//If the underlying view changes, this function will need to change as well
function format_output($row)
{
	return "<tr>\n\t<td>" . $row[0] . "</td>\n\t<td>" . $row[1] . "</td>\n\t<td>" . $row[2] . "</td>\n\t<td class='ralign'>" . $row[4] . "</td>\n</tr>\n";
}


?>
